/*******************************************************************************
* Copyright 2009, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/
/* ========================================
 *
 * This file is automatically generated by PSoC Creator
 * and should not be edited by hand.
 *
 * This file is necessary for your project to build.
 * Please do not delete it.
 *
 * ========================================
*/

#if !defined(DEVICE_H)
    #define DEVICE_H
	#define pi 3.14159265358979323846
	#include <project.h>

	enum {
	ok,
	bugEtat,
	bugConversionValeurTropGrande,
	erreurExecutionInstructionAvancer,
	erreurExecutionInstructionTourner,
	erreurExecutionInstructionAvancerNoB,
	erreurRxAsser,
	erreurRxXBee,
	erreurRxBalise
	};


	typedef struct robot{
		float direction;
		float positionX;
		float positionY;
	} robot ;



#endif

/*[]*/
